runtime: php
env: flex

runtime_config:
  document_root: web

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  MYSQL_HOST: /cloudsql/kathy-304221:us-central1:kattydb
  MYSQL_DB: test
  MYSQL_USER: root
  MYSQL_PASS: katty123
  MYSQL_PORT: 3306
  MYSQL_SOCKET: 
